# Generated by Django 3.1.4 on 2021-01-03 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0005_auto_20210103_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='modo_prepato',
            new_name='modo_preparo',
        ),
    ]
